const vocabularyData = [
    { word: "多元民族", pinyin: "duō yuán mín zú", defZh: "由多个不同民族组成的。", defEn: "Multi-ethnic / Diverse ethnic groups", defBm: "Pelbagai kaum", example: "马来西亚是一个多元民族的国家，各族和睦相处。" },
    { word: "和睦共处", pinyin: "hé mù gòng chǔ", defZh: "彼此友好、和平地相处。", defEn: "Live in harmony", defBm: "Hidup dalam harmoni", example: "各族群和睦共处，是国家的宝贵财富。" },
    { word: "互相包容", pinyin: "hù xiāng bāo róng", defZh: "彼此之间能够容忍和接纳不同的地方。", defEn: "Mutual tolerance / Acceptance", defBm: "Saling bertolak ansur", example: "社会需要互相包容，才能团结进步。" },
    { word: "印裔", pinyin: "yìn yì", defZh: "印度裔的，指有印度血统的人。", defEn: "Indian descent", defBm: "Keturunan India", example: "他是一位印裔同胞，从小在马来西亚长大。" },
    { word: "兼", pinyin: "jiān", defZh: "同时具有或涉及两个方面。", defEn: "Both / Simultaneously", defBm: "Sambil", example: "她学习优异，兼擅长各种运动。" },
    { word: "就读于", pinyin: "jiù dú yú", defZh: "在某所学校读书或学习。", defEn: "Study at", defBm: "Belajar di", example: "他目前就读于当地的一所华文小学。" },
    { word: "热衷于", pinyin: "rè zhōng yú", defZh: "对某件事非常感兴趣，全心投入。", defEn: "Keen on / Passionate about", defBm: "Sangat berminat", example: "她热衷于学习各种传统民俗技艺。" },
    { word: "历史悠久", pinyin: "lì shǐ yōu jiǔ", defZh: "有着很长的发展历史。", defEn: "Has a long history", defBm: "Mempunyai sejarah yang panjang", example: "舞狮是一项历史悠久的民俗技艺。" },
    { word: "民俗技艺", pinyin: "mín sú jì yì", defZh: "民间流传的手艺和技能。", defEn: "Folk art / Traditional craft", defBm: "Kesenian tradisional", example: "他从小就对各种民俗技艺充满好奇。" },
    { word: "巧遇", pinyin: "qiǎo yù", defZh: "碰巧遇到、偶然相遇。", defEn: "Coincidentally meet", defBm: "Secara kebetulan", example: "在文化节上，他巧遇了一位老艺人。" },
    { word: "缘分", pinyin: "yuán fèn", defZh: "人与人之间的一种奇妙联系。", defEn: "Fate / Destiny", defBm: "Nasib / Pertemuan", example: "他们因为共同的兴趣而结下了缘分。" },
    { word: "产生", pinyin: "chǎn shēng", defZh: "从已有的事物中生出新的事物。", defEn: "Generate / Produce", defBm: "Menghasilkan", example: "这次巧遇让他对舞狮产生了浓厚的兴趣。" },
    { word: "驻足", pinyin: "zhù zú", defZh: "停下脚步。", defEn: "Stop / Stand still", defBm: "Berhenti sebentar", example: "他被精彩的表演吸引，忍不住驻足观看。" },
    { word: "凑上前", pinyin: "còu shàng qián", defZh: "靠近上前。", defEn: "Move closer", defBm: "Menghampiri", example: "他好奇地凑上前，想看得更清楚。" },
    { word: "观赏", pinyin: "guān shǎng", defZh: "观看欣赏。", defEn: "Watch / Appreciate", defBm: "Melihat / Menikmati", example: "观众们都聚集在一起观赏舞狮表演。" },
    { word: "满腔热情", pinyin: "mǎn qiāng rè qíng", defZh: "心中充满热烈的感情和动力。", defEn: "Full of enthusiasm", defBm: "Penuh semangat", example: "他满腔热情地投入到了舞狮训练中。" },
    { word: "基本功", pinyin: "jī běn gōng", defZh: "从事某项活动必须掌握的基础技能。", defEn: "Basic skills / Fundamentals", defBm: "Asas", example: "练舞狮必须先打好基本功。" },
    { word: "门外汉", pinyin: "mén wài hàn", defZh: "对某方面没有深入了解的人。", defEn: "Outsider / Novice", defBm: "Orang baru", example: "刚开始时，他完全是个门外汉，什么都不懂。" },
    { word: "抛", pinyin: "pāo", defZh: "把东西向上或向外扔出。", defEn: "Throw / Toss", defBm: "Lontar", example: "舞狮时要把彩球抛到空中。" },
    { word: "绕", pinyin: "rào", defZh: "围绕着某个中心转圈。", defEn: "Twist / Circle", defBm: "Pusing", example: "他熟练地绕着狮头转动。" },
    { word: "甩", pinyin: "shuǎi", defZh: "用力挥动、摆动。", defEn: "Swing / Fling", defBm: "Hayun", example: "他用力一甩，狮子头就灵活地摆动起来。" },
    { word: "转", pinyin: "zhuàn", defZh: "旋转、转动。", defEn: "Spin / Turn", defBm: "Berputar", example: "他快速地转动身体，让狮头活灵活现。" },
    { word: "缠", pinyin: "chán", defZh: "把东西绕在一起。", defEn: "Wrap / Entwine", defBm: "Lilit", example: "表演者用彩带缠住了狮子的身体。" },
    { word: "金蝉脱壳", pinyin: "jīn chán tuō qiào", defZh: "比喻用计谋脱身。", defEn: "Escape by cunning", defBm: "Melarikan diri dengan taktik", example: "在表演中，他用了一招金蝉脱壳，观众们拍手叫好。" },
    { word: "招式", pinyin: "zhāo shì", defZh: "武术或表演中的动作技巧。", defEn: "Technique / Movement", defBm: "Jurus", example: "他认真地学习每一个舞狮招式。" },
    { word: "掌握", pinyin: "zhǎng wò", defZh: "理解并熟练运用。", defEn: "Master / Grasp", defBm: "Menguasai", example: "经过刻苦练习，他很快就掌握了基本动作。" },
    { word: "竞技", pinyin: "jìng jì", defZh: "比赛和竞争。", defEn: "Competition", defBm: "Pertandingan", example: "他参加了一场国际舞狮竞技比赛。" },
    { word: "阻碍", pinyin: "zǔ ài", defZh: "挡住前进的道路，造成困难。", defEn: "Obstacle / Hinder", defBm: "Halangan", example: "他遇到了很多阻碍，但没有放弃。" },
    { word: "流畅", pinyin: "liú chàng", defZh: "动作或语言非常自然、顺畅。", defEn: "Smooth / Fluent", defBm: "Lancar", example: "他的舞狮动作越来越流畅自然。" },
    { word: "趁闲暇", pinyin: "chèn xián xiá", defZh: "利用空闲的时间。", defEn: "In one's spare time", defBm: "Semasa lapang", example: "他经常趁闲暇时间练习舞狮。" },
    { word: "肌肉酸痛", pinyin: "jī ròu suān tòng", defZh: "肌肉因劳累而酸胀疼痛。", defEn: "Muscle soreness", defBm: "Sakit otot", example: "连续训练了几个小时后，他感到肌肉酸痛。" },
    { word: "粗糙", pinyin: "cū cāo", defZh: "不光滑，指技艺还不够细致。", defEn: "Rough / Crude", defBm: "Kasar", example: "刚开始时，他的动作还很粗糙，不够灵活。" },
    { word: "咬紧牙根", pinyin: "yǎo jǐn yá gēn", defZh: "用力咬牙忍受痛苦或困难。", defEn: "Grit one's teeth", defBm: "Gigi digigit", example: "即使全身酸痛，他仍然咬紧牙根继续训练。" },
    { word: "挫败", pinyin: "cuò bài", defZh: "受到挫折和失败。", defEn: "Frustration / Defeat", defBm: "Kegagalan", example: "面对挫败，他并没有气馁，反而更加努力。" },
    { word: "执着", pinyin: "zhí zhuó", defZh: "坚持自己的目标，不轻易放弃。", defEn: "Perseverance / Persistent", defBm: "Tekun", example: "他的执着精神终于换来了成功。" },
    { word: "毅力", pinyin: "yì lì", defZh: "坚强持久的意志力。", defEn: "Perseverance / Willpower", defBm: "Ketabahan", example: "舞狮训练需要极大的毅力和耐心。" },
    { word: "阻拦", pinyin: "zǔ lán", defZh: "阻挡、不让过去。", defEn: "Stop / Block", defBm: "Mencegah", example: "虽然家人曾想阻拦他，但他坚持要完成训练。" },
    { word: "努力耕耘", pinyin: "nǔ lì gēng yún", defZh: "比喻辛勤付出和努力。", defEn: "Work hard / Cultivate", defBm: "Bekerja keras", example: "只有努力耕耘，才能收获丰硕的成果。" },
    { word: "成果", pinyin: "chéng guǒ", defZh: "努力后的收获和成绩。", defEn: "Achievement / Result", defBm: "Hasil", example: "他的努力终于有了成果，在比赛中取得了好成绩。" },
    { word: "夸奖", pinyin: "kuā jiǎng", defZh: "用言语称赞别人。", defEn: "Praise / Compliment", defBm: "Memuji", example: "教练对他大加夸奖，说他进步神速。" },
    { word: "勤能补拙", pinyin: "qín néng bǔ zhuō", defZh: "勤奋可以弥补天资的不足。", defEn: "Diligence can make up for deficiency", defBm: "Kerajinan dapat menampung kekurangan", example: "他坚信勤能补拙，日复一日地刻苦训练。" },
    { word: "刮目相看", pinyin: "guā mù xiāng kàn", defZh: "用新的眼光来看待，表示进步很大。", defEn: "Look at with new admiration", defBm: "Pandang dengan mata baru", example: "他的表现让所有人对他刮目相看。" },
    { word: "出征", pinyin: "chū zhēng", defZh: "出发参加比赛或去执行任务。", defEn: "Set out / Go on a mission", defBm: "Bertolak", example: "他即将出征，参加国际锦标赛。" },
    { word: "经验", pinyin: "jīng yàn", defZh: "亲身经历后获得的知识和体会。", defEn: "Experience", defBm: "Pengalaman", example: "通过多次比赛，他积累了丰富的经验。" },
    { word: "体会", pinyin: "tǐ huì", defZh: "亲身感受、领悟。", defEn: "Realize / Understand", defBm: "Faham / Hayati", example: "他终于体会到了团队合作的重要性。" },
    { word: "身手", pinyin: "shēn shǒu", defZh: "身体的活动能力和动作技巧。", defEn: "Skill / Agility", defBm: "Kebolehan fizikal", example: "经过训练，他的身手变得非常敏捷。" },
    { word: "敏捷", pinyin: "mǐn jié", defZh: "动作迅速而灵活。", defEn: "Agile / Nimble", defBm: "Cergas", example: "他的动作敏捷，在比赛中表现出色。" },
    { word: "成就感", pinyin: "chéng jiù gǎn", defZh: "完成目标后的满足和自豪感。", defEn: "Sense of achievement", defBm: "Perasaan berjaya", example: "完成高难度的表演后，他充满了成就感。" },
    { word: "满足感", pinyin: "mǎn zú gǎn", defZh: "因愿望实现而感到满足。", defEn: "Sense of satisfaction", defBm: "Perasaan puas", example: "每一滴汗水都让他感到无比的满足感。" },
    { word: "非笔墨能形容", pinyin: "fēi bǐ mò néng xíng róng", defZh: "无法用言语来完全描述。", defEn: "Indescribable / Beyond words", defBm: "Tak dapat digambarkan", example: "他内心的喜悦非笔墨能形容。" },
    { word: "集训", pinyin: "jí xùn", defZh: "集中一段时间进行强化训练。", defEn: "Intensive training", defBm: "Latihan intensif", example: "赛前他们进行了为期三个月的集训。" },
    { word: "深感", pinyin: "shēn gǎn", defZh: "深深地感到。", defEn: "Deeply feel", defBm: "Sangat terasa", example: "他深感自己的责任重大。" },
    { word: "期许", pinyin: "qī xǔ", defZh: "期待、期望。", defEn: "Expectation", defBm: "Harapan", example: "家人对他寄予了很高的期许。" },
    { word: "纯熟", pinyin: "chún shú", defZh: "非常熟练、精通。", defEn: "Proficient / Skilled", defBm: "Mahir", example: "经过反复练习，他的动作已经非常纯熟。" },
    { word: "国际锦标赛", pinyin: "guó jì jǐn biāo sài", defZh: "多个国家选手参加的比赛。", defEn: "International championship", defBm: "Kejohanan antarabangsa", example: "他代表国家参加国际锦标赛。" },
    { word: "届时", pinyin: "jiè shí", defZh: "到了那时候。", defEn: "At that time", defBm: "Pada masa itu", example: "届时，各国选手都会齐聚一堂。" },
    { word: "辉煌", pinyin: "huī huáng", defZh: "非常灿烂、杰出。", defEn: "Brilliant / Glorious", defBm: "Cemerlang", example: "他期待能在赛场上创造辉煌的成绩。" },
    { word: "为国争光", pinyin: "wèi guó zhēng guāng", defZh: "为国家争取荣誉。", defEn: "Bring honor to one's country", defBm: "Mengharumkan nama negara", example: "他立志要在国际赛场上为国争光。" },
    { word: "宏愿", pinyin: "hóng yuàn", defZh: "远大的愿望和志向。", defEn: "Vow / Aspiration", defBm: "Azam", example: "他的宏愿是把舞狮艺术发扬光大。" },
    { word: "不禁赞叹", pinyin: "bù jīn zàn tàn", defZh: "不由自主地发出赞叹。", defEn: "Can't help admiring", defBm: "Tidak dapat menahan pujian", example: "看到他的精彩表演，观众们不禁赞叹。" },
    { word: "体悟", pinyin: "tǐ wù", defZh: "亲身领悟和感受。", defEn: "Realize / Reflect", defBm: "Memahami", example: "通过一次次的训练，他体悟到了坚持的意义。" },
    { word: "游走", pinyin: "yóu zǒu", defZh: "自由地穿梭、移动。", defEn: "Move freely", defBm: "Bergerak", example: "舞狮时，他在舞台上灵活地游走。" },
    { word: "发扬光大", pinyin: "fā yáng guāng dà", defZh: "把优秀的事物发展壮大。", defEn: "Promote and develop", defBm: "Memajukan / Mengembangkan", example: "他希望把舞狮这门传统艺术发扬光大。" }
];

// 将数据暴露为全局变量
var allIdioms = vocabularyData;
